<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134931760-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134931760-1');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Standard Error Handler in RxJava2 or why RxJava causes the application to crash even if onError is implemented</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="The translation of the article will deal with UndeliverableException in RxJava2 version 2.0.6 and newer. If someone collided and cannot understand, or...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6974184241884155",
            enable_page_level_ads: true
       });
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly.github.io/index.html"></a>
    <div class="page-header-text">Geekly Articles each Day</div>
  </header>
  <nav class="page-headings-container js-page-headings-container"></nav>
  <div class="tools-bar js-tools-bar">
    <!-- <a href="../../search.html" title="Search">üîé</a> -->
    <a class="js-list-of-headings-button" data-state="closed" href="#" title="Headings">üìú</a>
    <a class="js-go-to-top-button" href="#" title="Go to Top">‚¨ÜÔ∏è</a>
    <a class="js-go-to-bottom-button" href="#" title="Go to Bottom">‚¨áÔ∏è</a>
  </div>
  <a href="http://bit.ly/donateToWeeklyGeekly" class="donate-btn">DONATE</a>
  <section class="page js-page"><h1>Standard Error Handler in RxJava2 or why RxJava causes the application to crash even if onError is implemented</h1><div class="post__text post__text-html js-mediator-article"> The translation of the article will deal with <code>UndeliverableException</code> in <code>RxJava2</code> version <code>2.0.6</code> and newer.  If someone collided and cannot understand, or did not hear at all about this problem - I ask under cat.  Prompted to transfer the problem in <code>production</code> after the transition from <code>RxJava1</code> to <code>RxJava2</code> .  The original was written on December 28, 2017, but it‚Äôs better to learn late than never. <br><div style="text-align:center;"><img src="https://habrastorage.org/webt/sh/49/yi/sh49yi0mhl6-tmfir_fdvlkmcny.png"></div><a name="habracut"></a>  We are all good developers and we catch errors in <code>onError</code> when we use <code>RxJava</code> .  This means that we protected ourselves from the application crashes, right? <br><br>  <i>No, not right.</i> <br><br>  Below we look at a couple of examples in which an application will fall due to <code>RxJava</code> , even if <code>onError</code> correctly implemented. 
      <br>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <ins class="adsbygoogle"
          style="display:block; text-align:center;"
          data-ad-layout="in-article"
          data-ad-format="fluid"
          data-ad-client="ca-pub-6974184241884155"
          data-ad-slot="8945601208"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      <br>
    <h3>  Basic error handler in <code>RxJava</code> </h3><br>  In the role of the basic error handler in <code>RxJava</code> , <code>RxJavaPlugins.onError</code> used.  It handles all errors that cannot be delivered to the subscriber.  By default, all errors are sent exactly to it, so application crashes may occur. <br>  <a href=""><code>    2.0.6</code></a> this behavior is described: <br><blockquote>  One of the goals of 2.x design is the absence of lost bugs.  Sometimes the sequence ends or is canceled before the source calls <code>onError</code> .  In this case, the error has nowhere to go and it is sent to <code>RxJavaPlugins.onError</code> <br></blockquote><br>  If RxJava does not have a basic error handler, such errors will be hidden from us and the developers will be in the dark about potential problems in the code. <br><br>  Starting from version <code>2.0.6</code> , <code>RxJavaPlugins.onError</code> tries to be smarter and shares the library / implementation errors and situations when the error cannot be delivered.  Errors categorized as ‚Äúbugs‚Äù are caused as they are, the rest are wrapped in <code>UndeliverableException</code> and then called.  All this logic can be seen <a href="">here</a> ( <code>onError</code> and <code>isBug</code> ). <br><br>  One of the major bugs that newcomers face in <code>RxJava</code> is <code>OnErrorNotImplementedException</code> .  This error occurs when the <code>observable</code> causes an error, and the <code>onError</code> method is not implemented in the subscriber.  This error is an example of an error that for the basic error handler <code>RxJava</code> is a ‚Äúbug‚Äù and does not turn into a <code>UndeliverableException</code> . <br><br><h3>  UndeliverableException </h3><br>  Since the errors related to the "bugs" are easy to fix - we will not dwell on them.  The errors that <code>RxJava</code> wraps in a <code>UndeliverableException</code> are more interesting, since it may not always be obvious why an error cannot be delivered before <code>onError</code> . <br><br>  The cases in which this can occur depend on what the sources and subscribers specifically do.  Examples are discussed below, but in general we can say that such an error occurs if there is no active subscriber to whom an error can be delivered. <br><br><h3>  ZipWith () example </h3><br>  The first option in which you can call <code>UndeliverableException</code> is the <code>zipWith</code> . <br><br><pre> <code class="kotlin hljs"><span class="hljs-keyword"><span class="hljs-keyword">val</span></span> observable1 = Observable.error&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>&gt;(Exception()) <span class="hljs-keyword"><span class="hljs-keyword">val</span></span> observable2 = Observable.error&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>&gt;(Exception()) <span class="hljs-keyword"><span class="hljs-keyword">val</span></span> zipper = BiFunction&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>, String&gt; { one, two -&gt; <span class="hljs-string"><span class="hljs-string">"</span><span class="hljs-variable"><span class="hljs-string"><span class="hljs-variable">$one</span></span></span><span class="hljs-string"> - </span><span class="hljs-variable"><span class="hljs-string"><span class="hljs-variable">$two</span></span></span><span class="hljs-string">"</span></span> } observable1.zipWith(observable2, zipper) .subscribe( { System.<span class="hljs-keyword"><span class="hljs-keyword">out</span></span>.println(it) }, { it.printStackTrace() } )</code> </pre><br>  We combine together two sources, each of which causes an error.  What do we expect?  We can assume that <code>onError</code> will be called twice, but this is contrary <a href="">to the</a> <code>Reactive streams</code> <a href="">specification</a> . <br><blockquote>  After a single call to a terminal event ( <code>onError</code> , <code>onCompelete</code> ), it is required that no calls be made again. <br></blockquote><br>  It turns out that with a single <code>onError</code> call <code>onError</code> second call is no longer possible.  What happens when a second error occurs at the source?  It will be delivered to <code>RxJavaPlugins.onError</code> . <br><br>  A simple way to get into a similar situation is to use <code>zip</code> to join network calls (for example, two <code>Retrofit</code> calls that return <code>Observable</code> ).  If an error occurs in both calls (for example, there is no internet connection), both sources will cause errors, the first of which will go to the <code>onError</code> implementation, and the second will be delivered to the basic error handler ( <code>RxJavaPlugins.onError</code> ). <br><br><h3>  Example with ConnectableObservable without subscribers </h3><br>  <code>ConnectableObservable</code> can also cause <code>UndeliverableException</code> .  It is worth recalling that <code>ConnectableObservable</code> raises events regardless of the presence of active subscribers, just call the <code>connect()</code> method.  If there are no errors in <code>ConnectableObservable</code> if there are no subscribers, it will be delivered to the underlying error handler. <br><br>  Here is a rather innocent example that could cause such an error: <br><br><pre> <code class="kotlin hljs">someApi.retrofitCall() <span class="hljs-comment"><span class="hljs-comment">//     Retrofit .publish() .connect()</span></span></code> </pre><br>  If <code>someApi.retrofitCall()</code> causes an error (for example, there is no internet connection), the application will crash, since the network error will be delivered to the basic <code>RxJava</code> error <code>RxJava</code> . <br><br>  This example seems fictional, but it is very easy to get into a situation where the <code>ConnectableObservable</code> is still connected, but it has no subscribers.  I encountered this when using <code>autoConnect()</code> when calling the API.  <code>autoConnect()</code> does not automatically disable <code>Observable</code> .  I unsubscribed in the <code>onStop</code> method of the <code>Activity</code> , but the result of the network call was returned after the destruction of the <code>Activity</code> and the application <code>UndeliverableException</code> with <code>UndeliverableException</code> . <br><br><h3>  We process errors </h3><br>  So what to do with these errors? <br><br>  The first step is to look at the errors that occur and try to determine what causes them.  Ideally, if you manage to fix the problem at its source, to prevent the transmission of the error in <code>RxJavaPlugins.onError</code> . <br><br>  The solution to the <code>zipWith</code> example is to take one or both sources and implement <a href="https://github.com/ReactiveX/RxJava/wiki/Error-Handling-Operators">one of the methods</a> for catching errors in them.  For example, you can use <code>onErrorReturn</code> to pass a default value instead of an error. <br><br>  The example with <code>ConnectableObservable</code> easier to fix - just make sure you disconnect the <code>Observable</code> at the time when the last subscriber unsubscribes.  <code>autoConnect()</code> , for example, has an overloaded implementation that accepts a function that captures the connection point ( <a href="http://akarnokd.blogspot.com/2015/10/operator-internals-autoconnect.html">more can be found here</a> ). <br><br>  Another way to solve the problem is to replace the basic error handler with your own.  The <code>RxJavaPlugins.setErrorHandler(Consumer&lt;Throwable&gt;)</code> method will help you with this.  If this is a suitable solution for you, you can intercept all errors sent to <code>RxJavaPlugins.onError</code> and process them as you see fit.  This solution can be quite complicated - remember that <code>RxJavaPlugins.onError</code> receives errors from all streams of <code>RxJava</code> in the application. <br><br>  If you manually create your own <code>Observable</code> , you can call <code>emitter.tryOnError()</code> instead of <code>emitter.tryOnError()</code> .  This method sends an error only if the stream (stream) is not destroyed (terminated) and has subscribers.  Remember that this method is experimental. <br><br>  The moral of this article is that you cannot be sure that there are no errors when working with RxJava if you simply implemented <code>onError</code> in the subscribers.  You should be aware of situations in which errors may be inaccessible to subscribers, and make sure that these situations are handled. </div><p>Source: <a href="https://habr.com/ru/post/422611/">https://habr.com/ru/post/422611/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../422597/index.html">Backend United # 2: Minced</a></li>
<li><a href="../422601/index.html">Chrome 69 with random password generator released</a></li>
<li><a href="../422603/index.html">A little closer to perfection</a></li>
<li><a href="../422605/index.html">Grow safe from an early age - educational program of Rostelecom and MIPT</a></li>
<li><a href="../422609/index.html">Language barrier and NLP. Why don't chat bots understand us?</a></li>
<li><a href="../422613/index.html">Cybergroup PowerPool mastered the zero-day vulnerability in the Advanced Local Procedure Call</a></li>
<li><a href="../422615/index.html">The whole truth about the RTOS. Article # 9. Scheduler: implementation</a></li>
<li><a href="../422617/index.html">The whole truth about the RTOS. Article # 8. Nucleus SE: Inside and Deployment</a></li>
<li><a href="../422623/index.html">How to secure C</a></li>
<li><a href="../422625/index.html">We talked with Troy Miles, the programmer of Neuromant</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter52496797 = new Ya.Metrika({
                  id:52496797,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/52496797" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134931760-1', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

  <footer class="page-footer">
    <div class="page-footer-legal-info-container page-footer-element">
      <p>
        Weekly-Geekly | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
      </p>
    </div>
    <div class="page-footer-counters-container page-footer-element">
      <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=6iCFw7uJz0zcOaoxz5k5PcLCJUzv2WG8G5V8M3U6Rc4&co=3a3a3a&ct=ffffff'/></a>
    </div>
  </footer>
</body>

</html>