<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134931760-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134931760-1');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Error Handling in Node.js</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="The post contains a translation of the article ‚ÄúError Handling in Node.js‚Äù , which was prepared by Joyent employees. The article was published on Marc...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6974184241884155",
            enable_page_level_ads: true
       });
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly.github.io/index.html"></a>
    <div class="page-header-text">Geekly Articles each Day</div>
  </header>
  <nav class="page-headings-container js-page-headings-container"></nav>
  <div class="tools-bar js-tools-bar">
    <!-- <a href="../../search.html" title="Search">üîé</a> -->
    <a class="js-list-of-headings-button" data-state="closed" href="#" title="Headings">üìú</a>
    <a class="js-go-to-top-button" href="#" title="Go to Top">‚¨ÜÔ∏è</a>
    <a class="js-go-to-bottom-button" href="#" title="Go to Bottom">‚¨áÔ∏è</a>
  </div>
  <a href="http://bit.ly/donateToWeeklyGeekly" class="donate-btn">DONATE</a>
  <section class="page js-page"><h1>Error Handling in Node.js</h1><div class="post__text post__text-html js-mediator-article"><img src="https://habrastorage.org/getpro/habr/post_images/70e/ff3/1a3/70eff31a381e9dfa941ffcf0073a1a44.png"><br><br>  The post contains a translation of the article <a href="http://www.joyent.com/developers/node/design/errors">‚ÄúError Handling in Node.js‚Äù</a> , which was prepared by <a href="http://www.joyent.com/">Joyent</a> employees.  The article was published on March 28, 2014 on the company's website.  Dave Pacheco <a href="http://www.joyent.com/blog/best-practices-for-error-handling-in-node-js">explains</a> that the article is intended to eliminate the confusion among developers regarding the best practices for working with errors in Node.js, as well as to answer questions that often arise for novice developers. <br><a name="habracut"></a><br><h1>  Error Handling in Node.js </h1><br>  As you master Node.js, you can write programs for quite a long time, without paying due attention to correct error handling.  However, the development of serious projects on Node.js requires a conscious approach to this problem. <br><br>  Beginner developers often have the following questions: 
      <br>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <ins class="adsbygoogle"
          style="display:block; text-align:center;"
          data-ad-layout="in-article"
          data-ad-format="fluid"
          data-ad-client="ca-pub-6974184241884155"
          data-ad-slot="8945601208"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      <br>
    <ul><li> Is it possible to use <code>throw</code> to return an error from a function, or should a callback function be called passing the error object as an argument?  When do I need to generate an <code>'error'</code> event on an object of class EventEmitter? </li><li>  Do I need to check the arguments of the passed functions?  What if incorrect arguments are passed to the function?  In this case, is it necessary to generate an exception or call a callback function, passing an error to it? </li><li>  Is it possible to programmatically distinguish errors by type, so that the application can properly handle errors according to their type (for example, ‚ÄúBad Request‚Äù or ‚ÄúService Unavailable‚Äù)? </li><li>  How can a function inform the program in the most informative way about the occurrence of an error, so that it can process it correctly? </li><li>  Do I need to handle errors caused by "bugs" in the program? </li></ul><br><br>  This article consists of seven parts: <br><br><ol><li>  <strong>Introduction</strong>  The fact that the reader should know before reading the article. </li><li>  <strong>Software errors and programmer errors.</strong>  Familiarizing with the types of errors. </li><li>  <strong>Function writing templates.</strong>  Fundamental principles of writing functions that implement the correct work with errors. </li><li>  <strong>Rules for writing functions.</strong>  A list of instructions to follow when writing functions. </li><li>  <strong>Example.</strong>  An example of writing a function. </li><li>  <strong>Summary.</strong>  A brief presentation of the main provisions discussed in the article. </li><li>  <strong>Application.</strong>  Common field names for error objects. </li></ol><br><br><h2>  1. Introduction </h2><br>  It is assumed that the reader: <br><br><ul><li>  is familiar with the term ‚Äúexception‚Äù in JavaScript, Java, Python, C ++, or another similar language, and understands the principle of operation of the <code>try</code> / <code>catch</code> construct; </li><li>  familiar with the development on Node.js and mastered the principles of asynchronous programming. <br></li></ul><br>  The reader should understand why interception of exceptions does not work in the code below, despite the presence of a <code>try</code> / <code>catch</code> construct.  <sup>one</sup> <br><pre> <code class="javascript hljs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">function</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">myFunc</span></span></span><span class="hljs-function">(</span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">callback</span></span></span><span class="hljs-function">) </span></span>{ <span class="hljs-comment"><span class="hljs-comment">/* *     */</span></span> <span class="hljs-keyword"><span class="hljs-keyword">try</span></span> { doSomeAsyncOperation(<span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">function</span></span></span><span class="hljs-function"> (</span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">err</span></span></span><span class="hljs-function">) </span></span>{ <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (err) { <span class="hljs-keyword"><span class="hljs-keyword">throw</span></span> (err); } }); } <span class="hljs-keyword"><span class="hljs-keyword">catch</span></span> (ex) { callback(ex); } }</code> </pre><br>  The reader should be aware that in Node.js there are 3 main ways a function can return an error: <br><br><ol><li>  Throwing a <code>throw</code> error (throwing an exception). </li><li>  Call the callback function with the error object as the first argument. </li><li>  Generating an <code>'error'</code> event for an object of class EventEmitter. </li></ol><br>  It is assumed that the reader is not familiar with the <a href="http://nodejs.org/api/domain.html">domains</a> in Node.js. <br><br>  The reader must understand the difference between the error and the exception in JavaScript.  Error is any object of class <code>Error</code> .  The error can be created by the class constructor and returned from the function or thrown using the ThrowStatement instruction.  When an error object is thrown, an exception is thrown.  The following is an example of throwing an error (generating an exception): <sup>2</sup> <br><br><pre> <code class="javascript hljs"><span class="hljs-keyword"><span class="hljs-keyword">throw</span></span> <span class="hljs-keyword"><span class="hljs-keyword">new</span></span> <span class="hljs-built_in"><span class="hljs-built_in">Error</span></span>(<span class="hljs-string"><span class="hljs-string">' '</span></span>);</code> </pre><br>  An example where the error is passed to the callback function: <br><br><pre> <code class="javascript hljs">callback(<span class="hljs-keyword"><span class="hljs-keyword">new</span></span> <span class="hljs-built_in"><span class="hljs-built_in">Error</span></span>(<span class="hljs-string"><span class="hljs-string">' '</span></span>));</code> </pre><br>  The second option is more common in Node.js, due to the asynchrony of most operations performed.  As a rule, the first option is used only when data is deserialized (for example, <code>JSON.parse</code> ), while the thrown exception is caught using the <code>try</code> / <code>catch</code> construct.  This distinguishes Node.js from Java or C ++ and other languages ‚Äã‚Äãwhere you have to work with exceptions more often. <br><br><br><h2>  2. Software errors and programmer errors </h2><br>  Errors can be divided into two types: <sup>3</sup> <br><br><ul><li>  <strong>Software errors</strong> are conflicts that arise during the normal operation of a program.  They are not "bugs".  Usually, they are not directly related to the program: system errors (for example, memory overflow), configuration errors (for example, the remote server address is incorrect), Internet connection errors or errors that occurred on the remote server. <br>  Examples of software errors: <br><ul><li>  user entered incorrect data </li><li>  timeout for request response (timeout) expired, </li><li>  server responded to request with error code 500, </li><li>  disconnection </li><li>  allocated memory consumed. </li></ul><br></li><li>  <strong>Programmer errors</strong> are code defects that lead to incorrect program operation.  Errors of this type cannot be processed correctly, since the very fact of their presence indicates incorrectness of the written code.  Errors of this type can be eliminated by changing the program code.  Programmer errors include: <br><ul><li>  attempt to access a field with a value of <code>undefined</code> , </li><li>  call an asynchronous function without a callback function, </li><li>  function call with invalid arguments. </li></ul><br></li></ul><br>  Developers use the term ‚Äúerror‚Äù for both types of errors, despite their fundamental differences.  ‚ÄúFile not found‚Äù is a program error, its occurrence may mean that the program needs to create the desired file.  Thus, the occurrence of this error is not the incorrect behavior of the program.  Programmer errors, on the contrary, were not intended by the developer.  Perhaps the developer made a mistake in the name of the variable or incorrectly described the verification of data entered by the user.  This type of error cannot be processed. <br><br>  There may be cases when, for the same reason, both a program error and a programmer's error occur.  Suppose an HTTP server attempts to read a field with a value of <code>undefined</code> , which is a programmer‚Äôs error.  As a result, the server goes down.  The client, in <code>ECONNRESET</code> , receives an <code>ECONNRESET</code> error, usually described by Node.js as: ‚Äúsocket hang-up‚Äù, as a response to its request.  For a client, this is a software error and a correctly written client program will handle the error accordingly and continue to work. <br><br>  The absence of a program error handler is a programmer error.  Suppose that a client program, when establishing a connection with a server, encounters an ECONNREFUSED error, as a result, the connection object generates an <code>'error'</code> event, but no handler function is registered for this event, for this reason the program fails.  In this case, the connection error is a software error, however, the absence of a handler for the 'error' event of the connection object is a programmer's error. <br><br>  It is important to understand the differences between programmer errors and software errors.  Therefore, before continuing to read the article, make sure that you understand these concepts. <br><br><h3>  Error handling </h3><br>  Handling software errors, as well as issues of security or application performance, does not relate to the type of tasks that can be solved by implementing a module - it is impossible to solve all problems related to error handling in one place of the source code.  To solve the problem of error handling requires a decentralized approach.  For all areas of the program where an error is possible (access to the file system, connection to a remote server, creation of a child process, etc.), it is necessary to prescribe appropriate processing scripts for each possible type of error.  This means that it is necessary not only to highlight the problem areas, but also to understand what types of errors can occur in them. <br><br>  In some cases, it is necessary to transfer the error object from the function in which it originated through the callback function to a higher level, and from it even higher, thus the error ‚Äúpops up‚Äù until it reaches the logical level of the application that is responsible for processing this type of error.  At the responsible level, the program can decide: whether to launch the problem operation again, report the error to the user, or write the error information to the log file, etc. You should not always rely on this scheme and transmit errors to higher levels of the hierarchy, since callback functions at high levels do not know anything about the context in which the error transmitted to them occurred.  As a result, a situation may arise where at the selected logical level it will be difficult to describe the processing logic corresponding to the error that has occurred. <br><br>  Highlight possible error handling scenarios: <br><br><ul><li>  <strong>Elimination of errors.</strong>  Sometimes, the error can be eliminated.  Suppose an ENOENT error occurred while attempting to write information to a log file.  This may mean that the program has been launched for the first time and a log file has not yet been created.  In this case, the handler can resolve the error by creating the desired file.  Let us give a more interesting example: the program needs to constantly maintain a connection with a certain north (for example, with a database), but during the work a disconnection appeared.  In this case, the error handler may reconnect to the database. </li><li>  <strong>Informing the user and stop processing the request.</strong>  If you cannot solve the problem, the easiest way is to interrupt the current operation and inform the user about the error.  This scenario is applicable in cases where it is known that the reason for the error does not disappear over time.  For example, if an error occurred while trying to deserialize the JSON data transmitted by the client, there is no point in trying again with the same data. </li><li>  <strong>Repeat operation.</strong>  In case of network related errors, restarting the operation can help.  Suppose the program received an error 503 (Service Unavailable error) in response to a request to the remote service, in which case it may be worth repeating the request after a few seconds.  It is important to determine the final number of repetitions, as well as the frequency with which attempts should be performed.  But do not always rely on this scenario.  Suppose a user made a request to a certain service that needed to contact your program to process a request, and your program, in turn, makes a request to another service that responded with error 503. In this case, the best solution would be not to retry , and immediately give the opportunity to handle the error of the original service with which the user works.  If each service participating in the request chain makes repeated attempts, the user will wait for the response to his request longer than if only the original service performed them. </li><li>  <strong>Termination of the program.</strong>  If an unexpected situation has occurred, the appearance of which is impossible during the normal operation of the program, you should record the error information in the corresponding log file and stop working.  This scenario can be used if your program consumes available memory (however, if your program received an ENOMEM error from a child process, then the error can be processed and the program cannot be terminated).  Also, this scenario can be applied if your program does not have access rights to the files necessary for the work. </li><li>  <strong>Record errors in the log file and the continuation of the work.</strong>  In some cases, there is no need to stop the program even if the error that occurred is unrecoverable.  An example is the situation when your program periodically calls a group of remote services through the DNS system, and one of the services ‚Äúdropped out‚Äù of the DNS.  In this situation, the program can continue to work with the remaining services.  But, nevertheless, it is necessary to record the error in the log file.  (There are always exceptions for any rule, if an error occurs a thousand times a second, and you cannot do anything with it, then you do not need to write to the log each time, however, you should periodically log in.) </li></ul><br><h3>  Programmer Error Handling </h3><br>  There is no right way to handle programmer errors.  By definition, if such an error occurs, the program code is incorrect.  You can fix the problem only by correcting the code. <br><br>  There are programmers who believe that in some cases it is possible to restore a program after an error has occurred in such a way that the current operation is interrupted, but the program, nevertheless, continues to work and process other requests.  This is not recommended.  Taking into account that the programmer‚Äôs error puts the program in an unstable state, can you be sure that the error that occurred does not disrupt other requests?  If the requests work with the same entities (for example, a server, a socket, connections to a database, etc.), all that remains is to hope that subsequent requests will be processed correctly. <br><br>  Consider a REST service (implemented, for example, using the <a href="https://github.com/mcavage/node-restify">restify</a> module).  Suppose that one of the request handlers threw a <code>RefferenceError</code> exception because the programmer made a typo in the variable name.  If you do not immediately stop the service, there may be a number of problems that can be difficult to track: <br><br><ul><li>  If an entity as a result of a typo turns out to be <code>null</code> or <code>undefined</code> , then subsequent requests, turning to it, will also throw exceptions and will not be processed. </li><li>  If the function that threw the exception worked with the database, a connection could leak.  Each time a similar error occurs, the number of connections using which the service can work with the database will decrease. </li><li>  A more complicated situation can occur if postgres is used as the database and the connection is left unclosed during the execution of a transaction.  In this case, the "hung" transaction will not allow to clear the old versions of the records that are visible to it.  The transaction may remain open for weeks.  The size that the table occupies in memory will grow without restrictions, which will cause the processing of subsequent requests to slow down.  <sup>4</sup> Of course, this example is quite specific and concerns only postgres, however, it perfectly illustrates that it is dangerous to continue the work of a program that is in an unstable state. </li><li>  A connection to a remote service may remain with an unclosed session, as a result of which, the following request may be processed on behalf of the wrong user. </li><li>  May remain unclosed socket.  By default, Node.js will close an inactive socket in two minutes, but this behavior can be overridden, and if the error repeats, then the number of possible sockets will be exhausted.  If you leave the default configuration, it will be hard to track and fix the problem, since an error about an inactive socket occurs with a delay of two minutes. </li><li>  There may be a memory leak, which will lead to its overflow and program failure.  Or even worse - a leak can complicate the garbage collection process, which is why program performance will suffer.  Finding the cause of the problem in this case will be especially difficult. </li></ul><br>  Given the above, in such situations, the best solution would be to interrupt the program.  You can restart your program after it has been interrupted - this approach will automatically restore the stable operation of your service after any errors occur. <br>  The only, but significant, disadvantage of this approach is that all users working with the service will be disabled at the time of restart.  Keep in mind the following: <br><br><ul><li>  Crashes caused by a programmer error enter the application in an unstable state.  We must strive to ensure that such errors do not occur, their elimination has the highest priority. </li><li>  After a restart, requests can be executed correctly, and again lead to an error.  It may happen that requests are processed incorrectly, but it is difficult to track down the problem. </li><li>  In a well-designed system, regardless of whether an error is caused by a problem with an Internet connection or an error occurred in Node.js, the client program must be able to handle server errors (reconnect, perform repeated requests). </li></ul><br>  If the program is restarted very often, you should debug the code and fix the errors.  The best way to debug is to <a href="http://www.joyent.com/developers/node/debug">save and analyze the kernel snapshot</a> .  This approach works both in GNU / Linux-based systems and in illumos-systems, and allows you to view not only the sequence of functions that led to the error, but also the arguments passed to them, as well as the state of other objects that are visible through closures. <br><br><br><h2>  3. Patterns of writing functions </h2><br>  Firstly, it is worth noting that it is very important to document your functions in detail.  It is necessary to describe what the function returns, what arguments it takes and what errors may occur during the execution of the function.  If you do not define the types of possible errors and formulate what they mean, then you will not be able to correctly write a handler. <br><br><br><h3>  Throw, callback or EventEmitter? </h3><br>  There are three main ways to return an error from a function: <br><br><ol><li>  <code>throw</code> returns an error synchronously.  This means that an exception will occur in the same context in which the function was called.  If try / catch is used, the exception will be caught.  Otherwise, the program will fail (if, of course, the exception does not catch the domain or the event handler of the global object of the process <code>'uncaughtException'</code> , this option will be discussed later). </li><li>  callback-                 .    callback-    <code>callback(err, results)</code> ,           <code>null</code> . </li><li>         <code>'error'</code>   EventEmitter,    ,      <code>'error'</code> .    : <br><ul><li>   ,      .        .     EventEmitter    <code>'row'</code> ‚Äî    , <code>"end"</code> ‚Äî      <code>'error'</code> ‚Äî   . </li><li>     ,    .     ,   <code>'connect'</code> , <code>'end'</code> , <code>'timeout'</code> , <code>'drain'</code>  <code>'close'</code> .   ,     <code>'error'</code> .     ,      ,              . </li></ul><br></li></ol><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Using callback functions and generating events are related to asynchronous ways to return errors. </font><font style="vertical-align: inherit;">If an asynchronous operation is performed, then one of these methods is implemented, but both are never used at once. </font></font><br><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">So, when to use throw, and when to use callback-functions or events? </font><font style="vertical-align: inherit;">It depends on two factors:</font></font><br><br><ul><li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> error type (programmer error or program error), </font></font></li><li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> the type of function in which the error occurred (asynchronous or synchronous). </font></font></li></ul><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Software errors are more characteristic of asynchronous functions. Asynchronous functions take a callback function as an argument, when an error occurs, it is called with an error object as an argument. This approach has proven itself well and is widely used. As an example, see the Node.js module </font></font><code>fs</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">. The event approach is also used, but in more complex cases. </font></font><br><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Software errors in synchronous functions can occur, as a rule, if the function works with data entered by the user (for example, JSON.parse). In such functions, an error is thrown when an error occurs, more rarely an error object is returned by the return operator.</font></font><br><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">If a function has at least one of the possible errors asynchronous, then all possible errors should be returned from the function using the asynchronous approach. Even if the error occurred in the same context in which the function was called, the error object should be returned asynchronously. </font></font><br><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">There is an important rule: </font></font><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">for returning errors in the same function, either a synchronous or asynchronous approach can be implemented, but never both</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> . Then, in order to accept an error from a function, you will need to use either a callback function (or an event handler function </font></font><code>'error'</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">) or a try / catch construct, but never both. The documentation for the function should indicate which method is applicable to it.</font></font><br><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Verification of the input arguments as a rule allows you to prevent many errors that programmers make. It often happens that when you call an asynchronous function, they forget to transfer the callback function to it, as a result, in order to understand where an error occurs, the developer has to at least look at the stack of called functions. Therefore, if the function is asynchronous, then first of all, it is important to check whether the callback function is transmitted. If not passed, an exception must be generated. In addition, at the beginning of the function, you should check the types of the arguments passed to it, and also generate an exception if they are incorrect.</font></font><br><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Recall that programmer errors are not part of the normal process of the program. </font><font style="vertical-align: inherit;">They should not be caught and processed. </font><font style="vertical-align: inherit;">Therefore, these recommendations on the immediate throwing of exceptions in case of programmer errors do not contradict the rule formulated above that the same function should not implement both a synchronous and asynchronous approach for returning errors. </font></font><br><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Considered recommendations are presented in the table:</font></font><br><br><table><tbody><tr><td> <strong><nobr><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Function example</font></font></nobr></strong> </td><td align="right"> <strong><nobr><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Type of function</font></font></nobr></strong> </td><td align="left"> <strong><nobr><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Mistake</font></font></nobr></strong> </td><td align="left"> <strong><nobr><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Error type</font></font></nobr></strong> </td><td align="left"> <strong><nobr><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">How to return</font></font></nobr></strong> </td><td align="left"> <strong><nobr><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">How to handle</font></font></nobr></strong> </td></tr><tr><td> <code>fs.stat</code> </td> <td align="right"> <nobr><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">asynchronous</font></font></nobr> </td><td align="left"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> file not found </font></font></td><td align="left"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> software </font></font></td><td align="left"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> callback </font></font></td><td align="left"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> handler function </font></font></td></tr><tr><td> <code>JSON.parse</code> </td> <td align="right"> <nobr><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">synchronous</font></font></nobr> </td><td align="left"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> Input Error </font></font></td><td align="left"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> software </font></font></td><td align="left"> <code>throw</code> </td> <td align="left"> <code>try</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> / </font></font><code>catch</code> </td></tr><tr><td> <code>fs.stat</code> </td> <td align="right"> <nobr><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">asynchronous</font></font></nobr> </td><td align="left"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> missing required argument </font></font></td><td align="left"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> programmer error </font></font></td><td align="left"> <code>throw</code> </td> <td align="left"> <nobr><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">not processed </font></font></nobr> <br> <nobr><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">(termination of work)</font></font></nobr> </td></tr></tbody></table><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The first entry presents the most common example - the asynchronous function. </font><font style="vertical-align: inherit;">In the second line - an example for a synchronous function, this option is less common. </font><font style="vertical-align: inherit;">In the third line - a programmer's error, it is desirable that such cases take place only in the process of developing the program.</font></font><br><br><br><h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> Input Error: Programmer Error or Software Error? </font></font></h3><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">How to distinguish programmer errors from software errors? It is up to you to decide which data the transferred functions are correct and which are not. If arguments that do not meet your requirements are passed to the function, this is a programmer's mistake. If the arguments are correct, but the function cannot currently work with them, then this is a software error. </font></font><br><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">You have to decide how rigorously the argument is tested. Imagine a function </font></font><code>connect</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">that takes an IP address and a callback function as arguments. Suppose that this function was called with an argument that is different in format from the IP address, for example: "bob". Consider what can happen in this case:</font></font><br><br><ul><li>     ,       IPv4 ,         .     . </li><li>       ,      ,     IP- ¬´bob¬ª. </li></ul><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Both options satisfy the recommendations considered and it is up to you to decide how strictly to check. The Date.parse function, for example, accepts arguments of various formats, but for good reason. However, for most functions, it is recommended to strictly check the arguments passed. The more vague the criteria for checking arguments, the more difficult the process of debugging the code becomes. As a rule, the stricter the check, the better. And even if in future versions of the program you suddenly soften the criteria for checking inside some function, then you do not risk breaking your code. </font></font><br><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">If the transferred value does not meet the requirements (for example,</font></font><code>undefined</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">or the string has the wrong format), the function should report that the value passed is incorrect and terminate the program. </font><font style="vertical-align: inherit;">Stopping the work of the program by reporting incorrect arguments, you simplify the process of debugging code for yourself and other programmers.</font></font><br><br><br><h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> Domains and process.on ('uncaughtException') </font></font></h3><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Software errors can always be caught by a specific mechanism: through </font></font><code>try</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">/ </font></font><code>catch</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">, in the callback function or event handler </font></font><code>'error'</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">. </font><font style="vertical-align: inherit;">Domains and events of a global object </font></font><code>process</code> <code>'uncaughtException'</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">are often used to reinsure against unforeseen errors that a programmer could make. </font><font style="vertical-align: inherit;">Given the above considerations, this approach is strongly discouraged.</font></font><br><br><br><h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> 4. Rules for writing functions </font></font></h2><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> When writing functions, follow these rules: </font></font><br><br><ol><li> <strong>  </strong> <br>    .      : <br><ul><li>       ; </li><li>       ; </li><li>    ,      (: IP-    ). </li></ul><br>  -     ,      . <br>    : <br><ul><li>          (  ), </li><li>     (  <code>try</code> / <code>catch</code>    ), </li><li>    . </li></ul><br></li><li> <strong>   Error ( )   .</strong> <br>        Error  ,    .   <code>name</code>  <code>message</code> ,  <code>stack</code>     . <br><br></li><li> <strong>   ,    .</strong> <br>       ,      propertyName  propertyValue.           remoteIp,        .          <code>syscall</code> , ,      ,     <code>errno</code> ,      .        . <br><br>      : <br><ul><li> <code>name</code> :       . </li><li> <code>message</code> :    .    ,   ,       . </li><li> <code>stack</code> :      . V8      ,          ,        . </li></ul><br><br>     ,           ,      message  .       ,        . <br><br></li><li> <strong>       ,    .</strong> <br>    ,   ,      ,      callback-   ,    ,          ,       .           ¬´¬ª.                .  <a href="https://github.com/davepacheco/node-verror">verror</a>    . <br>    <code>fetchConfig</code> ,      .  <code>fetchConfig</code>     .     . <br><br><pre>    1.  <font></font>
      1.1    <font></font>
        1.1.1     DNS<font></font>
        1.1.2  TCP     <font></font>
        1.1.3     <font></font>
       1.2.     
       1.3.   
       1.4.  <font></font>
    2.   <font></font>
    </pre><br> ,    1.1.2  .           <code>fetchConfig</code>   ,       : <br><br><pre> <code class="javascript hljs">myserver: <span class="hljs-built_in"><span class="hljs-built_in">Error</span></span>: connect ECONNREFUSED</code> </pre><br>     . <br>       ,    : <br><br><pre> <code class="javascript hljs">myserver: failed to start up: failed to load configuration: failed to connect to database server: failed to connect to <span class="hljs-number"><span class="hljs-number">127.0</span></span><span class="hljs-number"><span class="hljs-number">.0</span></span><span class="hljs-number"><span class="hljs-number">.1</span></span> port <span class="hljs-number"><span class="hljs-number">1234</span></span>: connect ECONNREFUSED</code> </pre><br>       ,      : <br><br><pre> <code class="javascript hljs">myserver: failed to load configuration: connection refused <span class="hljs-keyword"><span class="hljs-keyword">from</span></span> database at <span class="hljs-number"><span class="hljs-number">127.0</span></span><span class="hljs-number"><span class="hljs-number">.0</span></span><span class="hljs-number"><span class="hljs-number">.1</span></span> port <span class="hljs-number"><span class="hljs-number">1234.</span></span></code> </pre><br> ,  ,   ‚Äî   . <br><br>       ,      : <br><br><ul><li>       ,       . </li><li>  <code>name</code>     ,     . ,    ,       ,       . </li><li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The field </font></font><code>message</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">during the wrapper can also be changed, but you should not change the message of the original object. </font><font style="vertical-align: inherit;">Do not perform any actions with the field </font></font><code>stack</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">, as mentioned above, V8 forms an object </font></font><code>stack</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">only when accessing it, and this is a fairly resource-intensive process that can lead to a significant decrease in the performance of your program.</font></font></li></ul><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">In Joyent, we use the </font></font><a href="https://github.com/davepacheco/node-verror"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">verror</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> module </font><font style="vertical-align: inherit;">for error wrapping, since it has a minimalistic syntax. </font><font style="vertical-align: inherit;">At the time of this writing, some of the recommendations reviewed have not been implemented in the module, but it will be finalized.</font></font><br><br></li></ol><br><br><h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> 5. Example </font></font></h2><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> Consider as an example the function that creates a TCP connection at the specified IPv4 address. </font></font><br><br><pre> <code class="javascript hljs"><span class="hljs-comment"><span class="hljs-comment">/* *   TCP    IPv4 . : * * ip4addr    IPv4; * * tcpPort  , TCP ; * * timeout  ,   ,    *      ; * * callback     , *    ,  *   callback(null, socket),  socket  *   net.Socket,   , *    callback(err). * *       : * * SystemError  "connection refused", "host unreachable"   * ,    connect(2).  *     errno  err   *    . * * TimeoutError       *   timeout. * *       "remoteIp"  "remotePort". *   , ,    ,  . */</span></span> <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">function</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">connect</span></span></span><span class="hljs-function">(</span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">ip4addr, tcpPort, timeout, callback</span></span></span><span class="hljs-function">) </span></span>{ assert.equal(<span class="hljs-keyword"><span class="hljs-keyword">typeof</span></span> (ip4addr), <span class="hljs-string"><span class="hljs-string">'string'</span></span>, <span class="hljs-string"><span class="hljs-string">" 'ip4addr'    "</span></span>); assert.ok(net.isIPv4(ip4addr), <span class="hljs-string"><span class="hljs-string">" 'ip4addr'   IPv4 "</span></span>); assert.equal(<span class="hljs-keyword"><span class="hljs-keyword">typeof</span></span> (tcpPort), <span class="hljs-string"><span class="hljs-string">'number'</span></span>, <span class="hljs-string"><span class="hljs-string">" 'tcpPort'    "</span></span>); assert.ok(!<span class="hljs-built_in"><span class="hljs-built_in">isNaN</span></span>(tcpPort) &amp;&amp; tcpPort &gt; <span class="hljs-number"><span class="hljs-number">0</span></span> &amp;&amp; tcpPort &lt; <span class="hljs-number"><span class="hljs-number">65536</span></span>, <span class="hljs-string"><span class="hljs-string">" 'tcpPort'        1  65535"</span></span>); assert.equal(<span class="hljs-keyword"><span class="hljs-keyword">typeof</span></span> (timeout), <span class="hljs-string"><span class="hljs-string">'number'</span></span>, <span class="hljs-string"><span class="hljs-string">" 'timeout'    "</span></span>); assert.ok(!<span class="hljs-built_in"><span class="hljs-built_in">isNaN</span></span>(timeout) &amp;&amp; timeout &gt; <span class="hljs-number"><span class="hljs-number">0</span></span>, <span class="hljs-string"><span class="hljs-string">" 'timeout'    "</span></span>); assert.equal(<span class="hljs-keyword"><span class="hljs-keyword">typeof</span></span> (callback), <span class="hljs-string"><span class="hljs-string">'function'</span></span>); <span class="hljs-comment"><span class="hljs-comment">/*   */</span></span> }</code> </pre><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> This example is rather primitive, but it illustrates many of the recommendations reviewed: </font></font><br><br><ul><li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> Arguments, their types, and requirements for them are documented in detail. </font></font></li><li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> The function checks the arguments passed to it and throws an exception if the arguments do not satisfy the criteria. </font></font></li><li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> The types of possible errors are documented, as well as the fields they contain. </font></font></li><li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> The way the function returns errors is specified. </font></font></li><li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> The returned errors have the ‚ÄúremoteIp‚Äù and ‚ÄúremotePort‚Äù fields, which will allow the handler to form an error message based on this information. </font></font></li><li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> The state of the connections after the occurrence of the error is documented: ‚Äúafter the occurrence of the error, the sockets that were opened by the function will be closed‚Äù. </font></font></li></ul><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> It may seem that in the presented example a lot of extra work has been done, however, ten minutes spent on writing documentation can save you or other developers a few hours. </font></font><br><br><br><h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> 6. Summary </font></font></h2><br><ul><li>      . </li><li>      ,         .          ,      . </li><li>           (, <code>throw</code> )    (callback-  ),        . ,   ,      ,     callback-,   try/catch,      . </li><li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">When writing functions, document in detail the arguments, their types, the requirements imposed on them, as well as the types of possible errors and how the function returns errors (synchronously, using </font></font><code>throw</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">, or asynchronously, using a callback function or event approach).</font></font></li><li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">The returned error must be an object of the class Error or a class of successor. </font><font style="vertical-align: inherit;">Expand the error object with new fields to include the necessary error information in the object. </font><font style="vertical-align: inherit;">If possible, use the common field names provided in the application.</font></font></li></ul><br><br><h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> 7. Appendix: common error field names </font></font></h2><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">It is strongly recommended that the field names in the table be used to extend error objects. </font><font style="vertical-align: inherit;">The presented names are used in standard Node.js modules, they should be used in error handlers, as well as when generating error messages.</font></font><br><table><tbody><tr><td align="left"> <strong><nobr>   </nobr></strong> </td><td align="left"> <strong> </strong> </td></tr><tr><td align="left"> <strong><code>localHostname</code></strong> </td> <td align="left">  DNS- <i>(, ,    )</i> </td></tr><tr><td align="left"> <strong><code>localIp</code></strong> </td> <td align="left">  IP- <i>(, ,    )</i> </td></tr><tr><td align="left"> <strong><code>localPort</code></strong> </td> <td align="left">  TCP  <i>(, ,    )</i> </td></tr><tr><td align="left"> <strong><code>remoteHostname</code></strong> </td> <td align="left"> DNS-   <i>(, ,    )</i> </td></tr><tr><td align="left"> <strong><code>remoteIp</code></strong> </td> <td align="left"> IP-   <i>(, ,    )</i> </td></tr><tr><td align="left"> <strong><code>remotePort</code></strong> </td> <td align="left">    <i>(, ,    )</i> </td></tr><tr><td align="left"> <strong><code>path</code></strong> </td> <td align="left">   ,      (IPC-) <i>(,   ,   )</i> </td></tr><tr><td align="left"> <strong><code>srcpath</code></strong> </td> <td align="left">      <i>(,   )</i> </td></tr><tr><td align="left"> <strong><code>dstpath</code></strong> </td> <td align="left">   <i>(,   )</i> </td></tr><tr><td align="left"> <strong><code>hostname</code></strong> </td> <td align="left"> DNS  <i>(, ,      IP-)</i> </td></tr><tr><td align="left"> <strong><code>ip</code></strong> </td> <td align="left"> IP- <i>(, ,      DNS-)</i> </td></tr><tr><td align="left"> <strong><code>propertyName</code></strong> </td> <td align="left">       <i>(,  ,       )</i> </td></tr><tr><td align="left"> <strong><code>propertyValue</code></strong> </td> <td align="left">    <i>(,  ,       )</i> </td></tr><tr><td align="left"> <strong><code>syscall</code></strong> </td> <td align="left">     </td></tr><tr><td align="left"> <strong><code>errno</code></strong> </td> <td align="left">   <code>errno</code> <i>(, <code>"ENOENT"</code> )</i> </td></tr></tbody></table><br><hr><br> <sup><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">1</font></font></sup><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> Novice developers often make a similar mistake. In this example, </font></font><code>try</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">/ </font></font><code>catch</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">and the call to the function that throws the exception will be executed in different contexts due to the asynchrony of the function </font></font><code>doSomeAsyncOperation</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">, so the exception will not be caught. </font></font><br> <sup><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2</font></font></sup><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> In JavaScript, it </font></font><code>throw</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">can work with values ‚Äã‚Äãof other types, but it is recommended to use objects of the Error class. If other values ‚Äã‚Äãare used in ThrowStatement, it will be impossible to get the call stack, which led to an error, which complicates debugging of the code. </font></font><br> <sup><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3</font></font></sup><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> These concepts emerged long before Node.js. In Java, an analogue can be considered checked and unchecked exceptions. </font></font><a href="http://en.wikipedia.org/wiki/Assertion_%2528software_development%2529"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Assertions are</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> provided in C for working with programmer errors </font><font style="vertical-align: inherit;">. </font></font><br> <sup><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">four</font></font></sup><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> The above example may seem too substantive, this is because it is not fictional, we really encountered this problem, it was unpleasant. </font></font></div><p>Source: <a href="https://habr.com/ru/post/222761/">https://habr.com/ru/post/222761/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../222745/index.html">The 7th meeting of the Odessa Testing community on May 22 in Ciklum</a></li>
<li><a href="../222747/index.html">The third meeting of the Kiev Android Community in Ciklum. Do not miss, it will be hot!</a></li>
<li><a href="../222749/index.html">Stylus for large smartphones</a></li>
<li><a href="../222751/index.html">Wiki resident and what it eats</a></li>
<li><a href="../222753/index.html">ASP.NET source code vNext published on Github</a></li>
<li><a href="../222763/index.html">15 sites in four countries have already joined PHDays Everywhere</a></li>
<li><a href="../222765/index.html">Elasticsearch as NoSQL database</a></li>
<li><a href="../222769/index.html">Intel¬Æ Composer XE 2015 Beta: reporting is fine!</a></li>
<li><a href="../222771/index.html">DevCon 2014 conference program published</a></li>
<li><a href="../222773/index.html">How can trust sociological research?</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter52496797 = new Ya.Metrika({
                  id:52496797,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/52496797" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134931760-1', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

  <footer class="page-footer">
    <div class="page-footer-legal-info-container page-footer-element">
      <p>
        Weekly-Geekly | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
      </p>
    </div>
    <div class="page-footer-counters-container page-footer-element">
      <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=6iCFw7uJz0zcOaoxz5k5PcLCJUzv2WG8G5V8M3U6Rc4&co=3a3a3a&ct=ffffff'/></a>
    </div>
  </footer>
</body>

</html>