<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134931760-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134931760-1');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>How to work with exceptions in DDD</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="In the framework of the recently held DotNext 2018 conference, the BoF on Domain Driven Design was held. It raised the issue of working with exception...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6974184241884155",
            enable_page_level_ads: true
       });
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly.github.io/index.html"></a>
    <div class="page-header-text">Geekly Articles each Day</div>
  </header>
  <nav class="page-headings-container js-page-headings-container"></nav>
  <div class="tools-bar js-tools-bar">
    <!-- <a href="../../search.html" title="Search">üîé</a> -->
    <a class="js-list-of-headings-button" data-state="closed" href="#" title="Headings">üìú</a>
    <a class="js-go-to-top-button" href="#" title="Go to Top">‚¨ÜÔ∏è</a>
    <a class="js-go-to-bottom-button" href="#" title="Go to Bottom">‚¨áÔ∏è</a>
  </div>
  <a href="http://bit.ly/donateToWeeklyGeekly" class="donate-btn">DONATE</a>
  <section class="page js-page"><h1>How to work with exceptions in DDD</h1><div class="post__text post__text-html js-mediator-article"><img src="https://habrastorage.org/webt/ue/vj/i6/uevji6om-hntwftu4kgfbt_mfsk.png" alt="image"><br><br>  In the framework of the recently held <a href="https://habr.com/company/jugru/blog/431194/">DotNext 2018</a> conference, the BoF on Domain Driven Design was held.  It raised the issue of working with exceptions, which caused a heated debate, but did not get a detailed discussion, since it was not the main topic. <br><br>  Also, studying a lot of resources, ranging from questions on stackoverflow and ending with paid courses on architecture, one can observe that the IT community has an ambiguous attitude towards exceptions and how to use them. 
      <br>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <ins class="adsbygoogle"
          style="display:block; text-align:center;"
          data-ad-layout="in-article"
          data-ad-format="fluid"
          data-ad-client="ca-pub-6974184241884155"
          data-ad-slot="8945601208"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      <br>
      Most often it is mentioned that with the use of exceptions it is easy to build a flow of execution that <a href="https://enterprisecraftsmanship.com/2015/02/26/exceptions-for-flow-control-in-c/">has the semantics of the goto operator</a> , which has a bad effect on the readability of the code. <br><br>  There are different opinions on whether to <a href="https://enterprisecraftsmanship.com/2016/12/08/custom-exception-types/">create your own types of exceptions</a> or use the standard ones supplied in .NET. <br><br>  Someone does validation on exceptions, and someone else <a href="https://enterprisecraftsmanship.com/2015/03/20/functional-c-handling-failures-input-errors/">uses the Result monad</a> .  It is fair that Result allows us to understand by the method signature whether it is possible not only successful execution.  But it is no less true that in imperative languages ‚Äã‚Äã(which include C #), the widespread use of Result leads to poorly readable code, filled with language constructs so that it is difficult to discern the original script. <br><br>  In this article I will talk about the practices adopted in our team (if briefly - we use all the approaches and none of them is a dogma). <br><br>  It will be a question of the enterprise-application constructed on the basis of ASP.NET MVC + WebAPI.  The application is built on the <a href="https://jeffreypalermo.com/2008/07/the-onion-architecture-part-1/">onion architecture</a> , communicates with a database and message broker.  Structured logging to the ELK stack is used and monitoring is configured with Grafana. <br><a name="habracut"></a><br>  We will look at work with exceptions from three angles: <br><br><ol><li>  General rules for dealing with exceptions </li><li>  Exceptions, Errors, and Onion Architecture </li><li>  Special cases for web applications </li></ol><br><h2>  General rules for dealing with exceptions </h2><br><ol><li>  Exceptions and errors are not the same thing.  For exceptions use exceptions, for errors - Result. </li><li>  Exceptions only for exceptional situations, which by definition can not be many.  This means there are fewer exceptions - the better. </li><li>  Exception handling should be as granular as possible.  As Richter wrote in his monumental work. </li><li>  If the error should be delivered to the user in its original form - use Result. </li><li>  The exception should not leave the system boundaries in their original form.  It is not user friendly and gives the attacker a way to further explore possible system weaknesses. </li><li>  If the thrown exception is processed by our application, we use not exception, but Result.  An implementation on exceptions will be a hidden goto statement and the worse the processing code is from the exception code of an exception, the worse it will be.  Result, on the other hand, explicitly declares the possibility of an error and allows only ‚Äúlinear‚Äù processing. </li></ol><br><h2>  Exceptions, Errors, and Onion Architecture </h2><br>  In the following sections, we will look at the responsibilities and rules for throwing / handling exceptions / errors for the following layers: <br><br><ul><li>  Application hosts </li><li>  Infrastructure </li><li>  Application services </li><li>  Domain core </li></ul><br><h3>  Application host </h3><br>  <b>What is responsible</b> <br><br><ul><li>  <a href="http://blog.ploeh.dk/2011/07/28/CompositionRoot/">Composition root</a> , customizing the work of the entire application. </li><li>  The boundary of interaction with the outside world - users, other services, scheduled launch. </li></ul><br>  Since these are quite complex responsibilities, it is worthwhile to limit them  The remaining responsibility is given to the inner layers. <br><br>  <b>How to handle errors from Result</b> <br><br>  Transmits to the outside world, transforming it into an appropriate format (for example, in http response). <br><br>  <b>How to generate a Result</b> <br><br>  No  This layer does not contain logic, so there is no place to generate errors. <br><br>  <b>How to handle exceptions</b> <br><br><ol><li>  Hides the details and converts to a format suitable for sending to the outside world </li><li>  Logs. </li></ol><br>  <b>How to throw exceptions</b> <br><br>  No, this layer is outermost and contains no logic - there is no one to give an exception to it. <br><br><h3>  Infrastructure </h3><br>  <b>What is responsible</b> <br><br><ol><li>  <a href="https://herbertograca.com/2017/09/14/ports-adapters-architecture/">Adapters to ports</a> , or simply implementations of Domain-interfaces, giving access to the infrastructure - third-party services, databases, active directory, etc. This layer should be as ‚Äústupid‚Äù as possible and contain as little logic as possible. </li><li>  If necessary, it can act as <a href="">Anti-corruption layer</a> . </li></ol><br>  <b>How to handle errors from Result</b> <br><br>  I am not aware of providers for databases and other services running on the Result monad.  However, some services operate on return codes.  In this case, convert them to the Result format required by the port. <br><br>  <b>How to generate a Result</b> <br><br>  In the general case, this layer does not contain logic, which means it does not generate errors.  But in the case of use as an anti corruption layer, a variety of options are possible.  For example, parsing exceptions from the legacy service and converting to Result those exceptions that are simple validation messages. <br><br>  <b>How to handle exceptions</b> <br><br>  In general, throws further, if necessary, pledge details.  If the port being implemented allows Result to be returned in the contract, then the infrastructure converts the types of exceptions that can be handled to Result. <br><br>  For example, a message broker used in a project throws exceptions when trying to send a message when the broker is unavailable.  The Application Services layer is ready for this situation and is able to handle it with the policy of Retry, Circuit Breaker or manual data rollback. <br><br>  In this case, the Application Services layer declares a contract that returns a Result in case of an error.  And the Infrastructure layer implements this port, converting the exception from the broker to Result.  Naturally, converts only specific types of exceptions, and not everything. <br><br>  Using this approach, we get two advantages: <br><br><ol><li>  Explicitly declare the possibility of errors in the contract. </li><li>  We get rid of the situation when the Application Service knows how to handle the error, but does not know the type of the exception, because it is abstracted from a particular message broker.  At the same time, building a catch block on the base System.Exception means to capture all types of exceptions, and not just those that the Application Service can handle. </li></ol><br>  <b>How to throw exceptions</b> <br><br>  Depends on the specifics of the system. <br><br>  For example, the LINQ operators Single and First, when requesting non-existent data, throw an InvalidOperationException exception.  But this type of exception is used everywhere in .NET, which makes it impossible to process it granularly. <br><br>  We in the team have taken the practice of creating custom ItemNotFoundException and throwing it from the infrastructure layer if the requested data is not found and should not be according to business rules. <br><br>  If the requested data is not found and it is acceptable - it is worth explicitly declaring it in the port contract.  For example, using the <a href="https://mikhail.io/2016/01/monads-explained-in-csharp/">Maybe monad</a> . <br><br><h3>  Application services </h3><br>  <b>What is responsible</b> <br><br><ol><li>  Validation of input data. </li><li>  Orchestration and coordination of services - starting and completing transactions, implementing distributed scripts, etc. </li><li>  Loading domain-objects and external data through the ports to the Infrastructure, the subsequent call commands in the Domain Core. </li></ol><br>  <b>How to handle errors from Result</b> <br><br>  Errors from the domain core transmits to the outside world without changes.  Errors from Infrastructure can process through policies Retry, Circuit Breaker or broadcast outside. <br><br>  <b>How to generate a Result</b> <br><br>  It can implement validation in the form of Result. <br><br>  May generate notifications of partial success of the operation.  For example, messages to the user of the form ‚ÄúYour order was successfully placed, but an error occurred while verifying the delivery address.  A specialist will contact you shortly to clarify the delivery details. ‚Äù <br><br>  <b>How to handle exceptions</b> <br><br>  Assuming that the infrastructure exceptions that the application is able to process have already been transformed by the Infrastructure layer into Result - it does not handle at all. <br><br>  <b>How to throw exceptions</b> <br><br>  In general, no way.  But there are borderline options described in the final section of the article. <br><br><h3>  Domain core </h3><br>  <b>What is responsible</b> <br><br>  The implementation of business logic, the ‚Äúcore‚Äù of the system and the main purpose of its existence. <br><br>  <b>How to handle errors from Result</b> <br><br>  Since the layer is internal and errors are possible only from objects in the same domain, processing is reduced either to business rules or to broadcasting the error upward in its original form. <br><br>  <b>How to generate a Result</b> <br><br>  If you violate business rules that are encapsulated in the Domain Core and are not covered by the validation of input data at the Application Services level.  In general, in this layer Result is used most often. <br><br>  <b>How to handle exceptions</b> <br><br>  No  Exceptions to the infrastructure have already been processed by the Infrastructure layer, the data have already come structured, complete and proven thanks to the Application Services layer.  Accordingly, all the exceptions that can take off are truly exceptions. <br><br>  <b>How to throw exceptions</b> <br><br>  Usually the general rule works here: the fewer exceptions, the better. <br><br>  But have you ever had a situation where you write code and understand that under certain conditions it can mess things up?  For example, twice to write off the money or so spoil the data that then we will not collect the bones. <br><br>  As a rule, we are talking about the execution of commands that are unacceptable for the current state of the object. <br><br>  Of course, the corresponding button on the UI should not be visible in this state.  We should not get a command from the bus in this state.  All this is true provided that the outer layers and systems performed their function <i>normally</i> .  But in Domain Core we do not need to know about the existence of external layers and believe in the correctness of their work, we must protect the invariants of the system. <br><br>  Some of the checks can be placed in Application Services at the level of validation.  But this can turn into <a href="https://en.wikipedia.org/wiki/Defensive_programming">defensive programming</a> , which in extreme cases leads to the following: <br><br><ol><li>  Encapsulation is weakened, since certain invariants must be tested on the outer layer. </li><li>  Knowledge of the subject area ‚Äúflow‚Äù into the outer layer, checks can be duplicated by both layers. </li><li>  Testing the <i>validity of</i> executing a command from the outer layer can be more complex and less reliable than checking the domain object with the <i>impossibility of</i> executing a command in the current state. </li></ol><br>  Also, if we place such checks in the validation layer, then we must tell the user the reason for the error.  Considering that we are talking about an operation that cannot be performed under current conditions at all, we risk being in one of two situations of a situation: <br><br><ul><li>  We gave the ordinary user a message that he did not understand at all and would still go to the support, as with the message "An unexpected error occurred." </li><li>  We quite clearly told the villain why he could not perform the operation he wanted to perform and he could look for other workarounds. </li></ul><br>  But back to the main topic of the article.  By all indications, the situation under discussion is exceptional.  It should never happen, but if it does, it will be bad. <br><br>  In this situation, it is most logical to throw an exception, log the necessary details, return the general error ‚ÄúOperation Impossible‚Äù to the user, set up monitoring for this type of errors and expect that we will never see them. <br><br>  What type or types of exceptions to use in this case?  Logically, this should be a separate type of exception, so that we can distinguish it from others and so that it does not accidentally be hooked by exception handling from the outer layer.  We, too, do not need a hierarchy or many exceptions, the essence is the same ‚Äî something unacceptable has happened.  We in our projects create for this the type CorruptedInvariantException, and use it in appropriate situations. <br><br><h2>  Special cases for web applications </h2><br>  A significant difference of web applications from others (desktop, demons and windows services, etc.) is interaction with the outside world in the form of short-term operations (processing HTTP requests), after which the application ‚Äúforgets‚Äù about what happened. <br><br>  Also, after the completion of the processing of a request, a response is always generated.  If the operation performed by our code does not return data, the platform will still return a response containing the status code.  If the operation was interrupted by an exception, the platform will still return a response containing the corresponding status code. <br><br>  To implement this behavior, processing requests in Web platforms is built in the form of pipelines (pipe).  At first, the request is processed and then the response is prepared. <br><br>  We can use middleware, action filter, http handler or ISAPI filter (depending on the platform) and integrate into this pipeline at any stage.  And at any stage of processing the request, we can interrupt processing and the pipeline will proceed to the formation of a response. <br><br>  The business part of the application, we, as a rule, are no longer implemented in the pipeline architecture, but we write code that performs operations sequentially.  And with this approach, it is somewhat more difficult to implement the script when we interrupt the execution of the request and immediately proceed to form the answer. <br><br>  What does all this have to do with exception handling, you ask? <br><br>  The fact is that the rules for working with exceptions described in the previous parts of the article do not fit well in this scenario. <br><br>  It is bad to use exceptions because it is goto semantics. <br><br>  Ubiquitous use of Result leads to the fact that we drag it (Result) across all layers of the application, and when forming the answer, you need to sort Result somehow in order to understand which return status code.  It is also desirable to summarize and parse this code in Middleware or ActionFilter, which becomes a separate adventure.  That is, Result is not much better than exceptions. <br><br>  <i>What to do in this situation?</i> <br><br>  Do not build an absolute.  We set the rules for our own benefit, not harm. <br><br>  If it is necessary to interrupt the operation, because its continuation is impossible, then the throwing of the exception will not have goto semantics.  We direct execution to the output, and not to another block of business code. <br><br>  If the reason for the interruption is important to determine the desired status code, you can use custom exception types. <br><br>  Earlier, we mentioned two custom types that we use: ItemNotFoundException (transform into 404) and CorruptedInvariant (transform into 500). <br><br>  If you check the rights of users, because they do not fall on the role model or claim, then it is permissible to create a custom ForbiddenException (Status code 403). <br><br>  And finally, validation.  We still can not do anything until the user modifies his query, this semantics <a href="https://developer.mozilla.org/ru/docs/Web/HTTP/Status/422">is described by code 422</a> .  So we interrupt the operation and send the request straight to the output.  It is also valid to do using exception.  For example, in the <a href="https://fluentvalidation.net/">FluentValidation</a> library, there is already a <a href="https://fluentvalidation.net/start">built-in exception type</a> that passes to the client all the details necessary to clearly display to the user what is wrong with the request. <br><br>  That's all.  And how do you work with exceptions? </div><p>Source: <a href="https://habr.com/ru/post/431804/">https://habr.com/ru/post/431804/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../431792/index.html">The digest of interesting materials for the mobile developer # 277 (November 26 - December 2)</a></li>
<li><a href="../431794/index.html">Proof of the Goldbach binary hypothesis</a></li>
<li><a href="../431796/index.html">NASA signs development lunar module development contracts with private companies</a></li>
<li><a href="../431800/index.html">Ministry of Communications proposes to entrust the creation of a 5G network to a single operator</a></li>
<li><a href="../431802/index.html">Problem personalities among project managers</a></li>
<li><a href="../431806/index.html">Palm Phone tested: the verdict - the developers have suffered a complete fiasco</a></li>
<li><a href="../431810/index.html">Test run with a three-axis accelerometer</a></li>
<li><a href="../431816/index.html">December 3, SpaceX will try to launch the first stage of the launch vehicle for the third time.</a></li>
<li><a href="../431818/index.html">Compare PHP FPM, PHP PPM, Nginx Unit, React PHP and RoadRunner</a></li>
<li><a href="../431820/index.html">Start to the ISS and braking at the asteroid</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter52496797 = new Ya.Metrika({
                  id:52496797,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/52496797" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134931760-1', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

  <footer class="page-footer">
    <div class="page-footer-legal-info-container page-footer-element">
      <p>
        Weekly-Geekly | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
      </p>
    </div>
    <div class="page-footer-counters-container page-footer-element">
      <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=6iCFw7uJz0zcOaoxz5k5PcLCJUzv2WG8G5V8M3U6Rc4&co=3a3a3a&ct=ffffff'/></a>
    </div>
  </footer>
</body>

</html>